language = "C"
cpp_compat = true
include_guard = "KINGOGFX_H"
namespace = "kgfx"

header = """
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4200) /* zero-sized array */
#endif
"""

trailer = """
#ifdef _MSC_VER
#pragma warning(pop)
#endif
"""

[defines]
"target_os = windows" = "KINGOGFX_PLATFORM_WINDOWS"